Repository VectorInstitute/vector-inference, pull requests merged in 2025-04, with the labels that each got.

#54 Add python API for programmatic access
  README.md
  docs/source/conf.py
  docs/source/index.md
  docs/source/reference/api/index.rst
  docs/source/reference/api/vec_inf.api.client.rst
  docs/source/reference/api/vec_inf.api.models.rst
  docs/source/reference/api/vec_inf.api.rst
  docs/source/reference/api/vec_inf.api.utils.rst
  docs/source/reference/api/vec_inf.rst
  docs/source/user_guide.md
  examples/README.md
  examples/api/basic_usage.py
  pyproject.toml
  tests/test_imports.py
  tests/vec_inf/cli/test_cli.py
  tests/vec_inf/cli/test_utils.py
  tests/vec_inf/client/__init__.py
  tests/vec_inf/client/test_api.py
  tests/vec_inf/client/test_examples.py
  tests/vec_inf/client/test_models.py
  tests/vec_inf/client/test_utils.py
  uv.lock
  vec_inf/cli/_cli.py
  vec_inf/cli/_helper.py
  vec_inf/cli/_models.py
  vec_inf/cli/_utils.py
  vec_inf/client/__init__.py
  vec_inf/client/_config.py
  vec_inf/client/_exceptions.py
  vec_inf/client/_helper.py
  vec_inf/client/_models.py
  vec_inf/client/_utils.py
  vec_inf/client/_vars.py
  vec_inf/client/api.py
Labels: enhancement

#91 Fix broken link in README, adjust codecov config
  README.md
  codecov.yml
Labels: documentation

#92 Add support for multiversion docs hosted via github pages
  .github/workflows/docs.yml
  docs/contributing.md
  docs/stylesheets/extra.css
  mkdocs.yml
  pyproject.toml
  uv.lock
Labels: documentation, enhancement

#94 Fix broken docs workflow, missed venv activate
  .github/workflows/docs.yml
Labels: bug, github_actions
